#!/usr/bin/python

import subprocess
import sys


def lazy_checkout(input_branch_name):
    command = ["git", "branch"]

    process = subprocess.Popen(command, stdout=subprocess.PIPE, stderr=subprocess.PIPE)

    output, error = process.communicate()

    if error:
        print error
        exit()

    git_branches = output.split('\n')

    matched_branch_names = []

    for branch in git_branches:
        branch = branch.replace('*', '').strip()

        if not len(branch) > 0: continue

        if input_branch_name not in branch: continue

        matched_branch_names.append(branch)

    if len(matched_branch_names) == 1:
        branch_selection = matched_branch_names[0]
    else:
        branch_selection = matched_branch_names[display_available_branches(matched_branch_names)]

    subprocess.call(["git", "checkout", branch_selection])


def display_available_branches(matchedBranchNames):
    selection_range = range(len(matchedBranchNames))

    for i in selection_range:
        selection_counter = i + 1
        print `selection_counter` + ") " + matchedBranchNames[i]

    selection = int_or_none(raw_input("Given branch name matches several available branches. Please select one: "))

    if selection is None or selection not in selection_range:
        selection = display_available_branches(matchedBranchNames)

    return selection


def int_or_none(input_string):
    try:
        return int(input_string)
    except ValueError:
        return None


if len(sys.argv) < 2:
    print "Invalid number of args"
    exit()

inputBranchName = sys.argv[1]

lazy_checkout(inputBranchName)